# Task1


In [1]:
import numpy as np

# Arrays
arr1 = np.arange(1, 11)
arr2 = np.arange(1, 10).reshape(3, 3)
arr3 = np.array([10, 20, 30, 40, 50])

# Print shapes and data types
print("arr1:", arr1, "Shape:", arr1.shape, "Dtype:", arr1.dtype)
print("arr2:\n", arr2, "Shape:", arr2.shape, "Dtype:", arr2.dtype)
print("arr3:", arr3, "Shape:", arr3.shape, "Dtype:", arr3.dtype)


arr1: [ 1  2  3  4  5  6  7  8  9 10] Shape: (10,) Dtype: int64
arr2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] Shape: (3, 3) Dtype: int64
arr3: [10 20 30 40 50] Shape: (5,) Dtype: int64


# Task2

In [2]:
A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])

print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)
print("Power:", A ** 2)

# Using NumPy functions
print("np.add:", np.add(A, B))
print("np.subtract:", np.subtract(A, B))


Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 100  400  900 1600]
np.add: [11 22 33 44]
np.subtract: [ 9 18 27 36]


# Task3

In [3]:
values = np.array([2, 4, 6, 8, 10])

print("Square root:", np.sqrt(values))
print("Exponential:", np.exp(values))
print("Natural log:", np.log(values))
print("Sum:", np.sum(values))
print("Cumulative sum:", np.cumsum(values))


Square root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Natural log: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum: 30
Cumulative sum: [ 2  6 12 20 30]


# Task4

In [4]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Row-wise sum:", np.sum(data, axis=1))
print("Column-wise sum:", np.sum(data, axis=0))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Overall mean:", np.mean(data))


Row-wise sum: [ 60 150 240]
Column-wise sum: [120 150 180]
Minimum: 10
Maximum: 90
Overall mean: 50.0


# Task5

In [5]:
marks = np.array([78, 85, 90, 66, 72, 88, 95, 60])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Variance:", np.var(marks))
print("Standard Deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Range:", np.max(marks) - np.min(marks))


Mean: 79.25
Median: 81.5
Variance: 134.1875
Standard Deviation: 11.583932838203095
Minimum: 60
Maximum: 95
Range: 35


# Task6

In [6]:
sorted_marks = np.sort(marks)
print("Sorted:", sorted_marks)

print("25th percentile:", np.percentile(marks, 25))
print("50th percentile:", np.percentile(marks, 50))
print("75th percentile:", np.percentile(marks, 75))

avg = np.mean(marks)
count_above_avg = np.sum(marks > avg)
print("Students above average:", count_above_avg)


Sorted: [60 66 72 78 85 88 90 95]
25th percentile: 70.5
50th percentile: 81.5
75th percentile: 88.5
Students above average: 4


# Task7

In [7]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

print("Total weekly sales:", np.sum(sales))
print("Average daily sales:", np.mean(sales))
print("Highest sales:", np.max(sales))
print("Lowest sales:", np.min(sales))
print("Standard deviation:", np.std(sales))

above_avg_days = sales[sales > np.mean(sales)]
print("Days with sales above average:", above_avg_days)


Total weekly sales: 10700
Average daily sales: 1528.5714285714287
Highest sales: 2000
Lowest sales: 900
Standard deviation: 345.2298849598449
Days with sales above average: [2000 1800 1700 1600]
